"""empty message

Revision ID: 249e58d85248
Revises: c0c7a7a5ff39
Create Date: 2024-09-14 20:59:50.310438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249e58d85248'
down_revision = 'c0c7a7a5ff39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
